### PR TITLE
Add a fixer for instances of `unichr`

### PR DESCRIPTION
**Pull request by rowillia**
This can be trivially fixed by using the six unichr shim.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, this looks good to me. I'll give others a chance to look at it.

**Comment by rowillia** [comment]
Thanks @takluyver !  @daira What do you think?

**Comment by brettcannon** [comment]
LGTM as well. @takluyver want me to merge this?

**Comment by takluyver** [comment]
Actually, just spotted that the naming and one of the tests treat `unichr` as a type, whereas it's a function. You can't do `isinstance(x, chr)` on Py3, nor `isinstance(x, unichr)` on Py2.

**Comment by rowillia** [comment]
@takluyver Done

**Comment by brettcannon** [comment]
Tweak LGTM

**Comment by takluyver** [comment]
Thanks, this looks good to me, but it has merge conflicts now that Brett merged #146.

**Comment by rowillia** [comment]
@brettcannon @takluyver rebased.

**Comment by takluyver** [comment]
Thanks

**Pull request merged**
