### PR TITLE
Add a fixer for urllib based off of 2to3.

### PR DESCRIPTION
**Pull request by rowillia**
This will help projects using urllib port to Python 3.

### CODE REVIEW

**Comment by rowillia** [comment]
@takluyver @daira Ping!  Anything I can do here for you folks?

**Comment by brettcannon** [comment]
Could you add some more tests, @rowillia , like something from urllib2 and then a test from different submodules like six.moves.urllib.parse?

**Comment by rowillia** [comment]
@brettcannon Done!  Thanks for taking a look.

**Comment by takluyver** [comment]
Thanks!

@brettcannon, go ahead and merge if you're happy with it now.

**Comment by brettcannon** [comment]
LGTM, so merged. Thanks, @rowillia !

**Pull request merged**
